name: Generate Metrics

on:
  schedule:
    - cron: '0 */3 * * *'  # 每 3 小時運行一次
  workflow_dispatch:       # 允許手動觸發
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 檢出你的 repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 生成 Isometric Commit Calendar（半年度版本）
      - name: Generate Isometric Commit Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

      # 3. 生成 Music Plugin 圖片 - Spotify 最近播放
      # - name: Generate Music Plugin - Recently Listened
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.music.recent.svg
      #     token: NOT_NEEDED
      #     base: ""
      #     plugin_music: yes
      #     plugin_music_provider: spotify
      #     plugin_music_mode: recent
      #     plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
      #     plugin_music_limit: 2

      # 4. 生成 Terminal Template 圖片
      - name: Generate Terminal Template
        uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata

      # 5. 生成 Starred Topics 插件圖片
      - name: Generate Topics Plugin
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: starred
          plugin_topics_sort: stars

      # 6. 生成 Coding Habits 插件 - Mildly interesting facts
      - name: Generate Coding Habits Facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Europe/Paris

      # 7. 生成 Coding Habits 插件 - Recent activity charts
      - name: Generate Coding Habits Charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris

      - name: JavaScript or TypeScript snippet of the day
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: javascript, typescript, python
          plugin_code_load: 400
          plugin_code_visibility: all

          
      - name: Youtube Music - Recently listed
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.youtube.svg
          token: NOT_NEEDED
          base: ""
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKENS }}
          plugin_music: yes
          plugin_music_mode: recent
          plugin_music_provider: youtube
          plugin_music_limit: 5

      - name: Favorites anime and currently watching
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: ken22i
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 5

      - name: Favorites characters
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: ken22i
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22

      # 8. 複製產生的 SVG 檔案並 commit
      - name: Copy and Commit Metrics
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          # 將 /metrics_renders/ 內的所有 SVG 檔案複製到工作目錄
          cp -v /metrics_renders/*.svg .
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit --allow-empty -m "Update metrics [skip ci]" || echo "No changes to commit"
          git push --force https://${METRICS_TOKEN}@github.com/ken22i/ken22i.git
